- name: install dnsmasq
  apt: name=dnsmasq state=present

- name: dnsmasq configuration file
  template: src=dnsmasq.conf.j2 dest=/etc/dnsmasq.conf
  notify: restart dnsmasq

- name: dnsmasq service stateg
  service: name=dnsmasq state=started enabled=yes

- name: make sure dnsmasq is running
  service: name=dnsmasq state=running
